version: "3.9"
services:
    php:
        environment:
            XDEBUG_MODE: "debug"
            XDEBUG_CONFIG: "client_port=9003"
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        volumes:
            - type: bind
              source: .
              target: /app
        expose:
            - 9000
            - 9003
        networks:
            - net
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        volumes:
            - type: volume
              source: data_postgres
              target: /var/lib/postgresql/data
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
        ports:
            - "5432:5432"
        expose:
            - 5432
        networks:
            - net

    nginx:
        image: nginx:1.20
        volumes:
            - type: bind
              source: .
              target: /app
            - type: bind
              source: docker/nginx/
              target: /etc/nginx/conf.d/
        ports:
            - "80:80"
        expose:
            - 80
        networks:
            - net
        depends_on:
            - php
            - postgres
volumes:
    data_php-fpm:
    data_postgres:
networks:
    net:
        driver: bridge
